/*!
 Defines routines for converting sticker image files.
*/

use std::{
    env::temp_dir,
    fs::{create_dir_all, read_dir, remove_dir_all},
    path::{Path, PathBuf},
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use imessage_database::tables::attachment::MediaType;

use crate::app::compatibility::{
    converters::common::{copy_raw, ensure_paths, run_command},
    models::{Converter, ImageConverter, ImageType, VideoConverter},
};

/// Copy a sticker, converting if possible
///
/// - Sticker `HEIC` files convert to `PNG`
/// - Sticker `HEICS` files convert to `GIF`
/// - Fallback to the original format
pub(crate) fn sticker_copy_convert(
    from: &Path,
    to: &mut PathBuf,
    image_converter: &ImageConverter,
    video_converter: Option<&VideoConverter>,
    mime_type: &MediaType,
) -> Option<MediaType<'static>> {
    // Determine the output type of the sticker
    let output_type: Option<ImageType> = match mime_type {
        // Normal stickers get converted to png
        MediaType::Image("heic" | "HEIC") => Some(ImageType::Png),
        MediaType::Image("heics" | "HEICS" | "heic-sequence") => Some(ImageType::Gif),
        _ => None,
    };

    if let Some(output_type) = output_type {
        // Update extension for conversion
        let mut converted_path = to.clone();
        converted_path.set_extension(output_type.to_str());

        // If the attachment is an animated sticker, attempt to convert it to a gif
        // Fall back to the normal converter if this fails
        if matches!(output_type, ImageType::Gif)
            && let Some(video_converter) = video_converter
        {
            if convert_heics(from, &converted_path, video_converter).is_some() {
                *to = converted_path;
                return Some(MediaType::Image(output_type.to_str()));
            }
            eprintln!("Unable to convert {}", from.display());
        }

        // Standard `HEIC` converter fallback
        if convert_heic(from, &converted_path, image_converter, &output_type).is_some() {
            *to = converted_path;
            return Some(MediaType::Image(output_type.to_str()));
        }
        eprintln!("Unable to convert {}", from.display());
    }

    // Fallback
    copy_raw(from, to);
    None
}

/// Convert a HEIC sticker file to the provided format
///
/// This uses the macOS builtin `sips` program or `ImageMagick`
///
/// Docs: <https://www.unix.com/man-page/osx/1/sips/> (or `man sips`)
///
/// If `to` contains a directory that does not exist, i.e. `/fake/out.jpg`, instead
/// of failing, `sips` will create a file called `fake` in `/`. Subsequent writes
/// by `sips` to the same location will not fail, but since it is a file instead
/// of a directory, this will fail for non-`sips` copies.
///
/// Sticker HEIC files contain 5 images: 320x320, 160x160, 96x96, 64x64, and 40x40
///
/// `magick` attempts to extract all of them; but for compatibility purposes we only
/// take the highest resolution. This is done automatically in `sips` but requires
/// manual adjustment in `magick`: <https://github.com/ImageMagick/ImageMagick/issues/1391>
fn convert_heic(
    from: &Path,
    to: &Path,
    converter: &ImageConverter,
    output_image_type: &ImageType,
) -> Option<()> {
    let (from_path, to_path) = ensure_paths(from, to)?;

    match converter {
        ImageConverter::Sips => {
            let args = vec![
                "-s",
                "format",
                output_image_type.to_str(),
                from_path,
                "-o",
                to_path,
            ];
            run_command(converter.name(), args)
        }
        ImageConverter::Imagemagick => {
            let formatted_from = format!("{from_path}[0]");
            let args = vec![&formatted_from, to_path];
            run_command(converter.name(), args)
        }
    }
}

fn convert_heics(from: &Path, to: &Path, video_converter: &VideoConverter) -> Option<()> {
    let tmp_path = unique_tmp_dir()?;
    let result = convert_heics_with_tmp(from, to, video_converter, &tmp_path);
    // Best-effort cleanup of the per-call scratch directory, regardless of outcome.
    let _ = remove_dir_all(&tmp_path);
    result
}

fn convert_heics_with_tmp(
    from: &Path,
    to: &Path,
    video_converter: &VideoConverter,
    tmp_path: &Path,
) -> Option<()> {
    let (from_path, to_path) = ensure_paths(from, to)?;

    // Frames per second in the original sticker, generated by Apple
    let fps = 10;

    let tmp = tmp_path.to_str()?;

    match video_converter {
        VideoConverter::Ffmpeg => {
            // HEICS format contains 4 video streams
            // The first one is the first still
            // Stream #0:0[0x1]: Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, smpte170m/unknown/unknown), 524x600, 1 fps, 1 tbr, 1 tbn (default)
            // The second one is the alpha mask for the first still
            // Stream #0:1[0x2]: Video: hevc (Rext) (hvc1 / 0x31637668), gray(pc), 524x600, 1 fps, 1 tbr, 1 tbn

            // The third stream is the video data
            // Stream #0:2[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, smpte170m/unknown/unknown), 524x600, 1370 kb/s, 22.98 fps, 30 tbr, 600 tbn (default)
            run_command(
                video_converter.name(),
                vec![
                    "-i",
                    from_path,
                    "-map",
                    "0:2",
                    "-y",
                    &format!("{tmp}/frame_%04d.png"),
                ],
            )?;

            // The fourth stream is the alpha mask
            // Stream #0:3[0x2](und): Video: hevc (Rext) (hvc1 / 0x31637668), gray(pc), 524x600, 426 kb/s, 22.98 fps, 30 tbr, 600 tbn (default)
            run_command(
                video_converter.name(),
                vec![
                    "-i",
                    from_path,
                    "-map",
                    "0:3",
                    "-y",
                    &format!("{tmp}/alpha_%04d.png"),
                ],
            )?;

            // This step applies the transparency mask to the images.
            // Discover the actual frame files emitted by ffmpeg rather than
            // counting-and-indexing, so the loop matches whatever start
            // number ffmpeg used.
            let mut frames: Vec<PathBuf> = read_dir(tmp_path)
                .ok()?
                .flatten()
                .map(|entry| entry.path())
                .filter(|path| {
                    path.file_name()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| name.starts_with("frame_") && name.ends_with(".png"))
                })
                .collect();
            frames.sort();

            let mut first_merged: Option<PathBuf> = None;
            for frame in &frames {
                let stem = frame.file_stem()?.to_str()?;
                let index = stem.strip_prefix("frame_")?;
                let alpha = tmp_path.join(format!("alpha_{index}.png"));
                if !alpha.exists() {
                    continue;
                }
                let merged = tmp_path.join(format!("merged_{index}.png"));
                run_command(
                    video_converter.name(),
                    vec![
                        "-i",
                        frame.to_str()?,
                        "-i",
                        alpha.to_str()?,
                        "-filter_complex",
                        "[1:v]format=gray,geq=lum='p(X,Y)':a='p(X,Y)'[mask];[0:v][mask]alphamerge",
                        merged.to_str()?,
                    ],
                )?;
                if first_merged.is_none() {
                    first_merged = Some(merged);
                }
            }
            let first_merged = first_merged?;

            // Once we have the transparent frames,
            // we use the first frame to generate a transparency palette
            run_command(
                video_converter.name(),
                vec![
                    "-i",
                    first_merged.to_str()?,
                    "-vf",
                    "palettegen=reserve_transparent=1",
                    &format!("{tmp}/palette.png"),
                ],
            )?;

            // Create the gif from the parts we parsed above
            run_command(
                video_converter.name(),
                vec![
                    "-i",
                    &format!("{tmp}/merged_%04d.png"),
                    "-i",
                    &format!("{tmp}/palette.png"),
                    "-lavfi",
                    &format!("fps={fps},paletteuse=alpha_threshold=128"),
                    "-gifflags",
                    "-offsetting",
                    to_path,
                ],
            )?;

            Some(())
        }
    }
}

/// Create a unique scratch directory under the platform temp dir.
///
/// Names include the process ID and a nanosecond timestamp so that
/// concurrent invocations do not collide on filesystem state.
fn unique_tmp_dir() -> Option<PathBuf> {
    let suffix = format!(
        "imessage-stickers-{}-{}",
        process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .ok()?
            .as_nanos(),
    );
    let path = temp_dir().join(suffix);
    if let Err(why) = create_dir_all(&path) {
        eprintln!("Unable to create {}: {why}", path.display());
        return None;
    }
    Some(path)
}
