/*!
 Collaboration link previews generated by apps such as Pages and Freeform.
*/

use plist::Value;

use crate::{
    error::plist::PlistParseError,
    message_types::variants::{BalloonProvider, HasUrl},
    util::plist::{
        get_float_from_nested_dict, get_string_from_dict, get_string_from_nested_dict,
        rich_link_metadata_and_nested,
    },
};

/// This struct is not documented by Apple, but represents messages displayed as
/// `com.apple.messages.URLBalloonProvider` but from [Rich Collaboration](https://developer.apple.com/videos/play/wwdc2022/10095/) messages
#[derive(Debug, PartialEq)]
pub struct CollaborationMessage<'a> {
    /// URL used to open or join the share session.
    pub original_url: Option<&'a str>,
    /// Unique URL for the collaboration item.
    pub url: Option<&'a str>,
    /// Title of the shared file.
    pub title: Option<&'a str>,
    /// Raw creation timestamp from the payload.
    pub creation_date: Option<f64>,
    /// Bundle ID of the application that generated the message.
    pub bundle_id: Option<&'a str>,
    /// Display name of the application that generated the message.
    pub app_name: Option<&'a str>,
}

impl<'a> BalloonProvider<'a> for CollaborationMessage<'a> {
    fn from_map(payload: &'a Value) -> Result<Self, PlistParseError> {
        if let Ok((base, meta)) = rich_link_metadata_and_nested(payload, "collaborationMetadata") {
            return Ok(Self {
                original_url: get_string_from_nested_dict(base, "originalURL"),
                url: get_string_from_dict(meta, "collaborationIdentifier"),
                title: get_string_from_dict(meta, "title"),
                creation_date: get_float_from_nested_dict(meta, "creationDate"),
                bundle_id: CollaborationMessage::get_bundle_id(meta),
                app_name: CollaborationMessage::get_app_name(base),
            });
        }
        Err(PlistParseError::NoPayload)
    }
}

impl<'a> CollaborationMessage<'a> {
    /// Extract the bundle ID from `containerSetupInfo`.
    fn get_bundle_id(payload: &'a Value) -> Option<&'a str> {
        payload
            .as_dictionary()?
            .get("containerSetupInfo")?
            .as_dictionary()?
            .get("containerID")?
            .as_dictionary()?
            .get("ContainerIdentifier")?
            .as_string()
    }

    /// Extract the application name from `richLinkMetadata`.
    fn get_app_name(payload: &'a Value) -> Option<&'a str> {
        payload
            .as_dictionary()?
            .get("specialization2")?
            .as_dictionary()?
            .get("specialization")?
            .as_dictionary()?
            .get("application")?
            .as_string()
    }

    /// Resolve this message's URL via [`HasUrl::get_url`].
    #[must_use]
    pub fn get_url(&self) -> Option<&str> {
        <Self as HasUrl>::get_url(self)
    }
}

impl HasUrl for CollaborationMessage<'_> {
    fn url(&self) -> Option<&str> {
        self.url
    }

    fn original_url(&self) -> Option<&str> {
        self.original_url
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        message_types::{collaboration::CollaborationMessage, variants::BalloonProvider},
        util::plist::parse_ns_keyed_archiver,
    };
    use plist::Value;
    use std::env::current_dir;
    use std::fs::File;

    #[test]
    fn test_parse_collaboration() {
        let plist_path = current_dir()
            .unwrap()
            .as_path()
            .join("test_data/collaboration_message/Freeform.plist");
        let plist_data = File::open(plist_path).unwrap();
        let plist = Value::from_reader(plist_data).unwrap();
        let parsed = parse_ns_keyed_archiver(&plist).unwrap();

        let actual = CollaborationMessage::from_map(&parsed).unwrap();
        let expected = CollaborationMessage {
            original_url: Some("https://www.icloud.com/freeform/REDACTED#Untitled"),
            url: Some("https://www.icloud.com/freeform/REDACTED"),
            title: Some("Untitled"),
            creation_date: Some(695179243.070923),
            bundle_id: Some("com.apple.freeform"),
            app_name: Some("Freeform"),
        };

        assert_eq!(actual, expected);
    }
}
