name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release
      - develop

env:
  CARGO_TERM_COLOR: always
  TZ: America/Los_Angeles

jobs:
  Test:
    name: iMessage Exporter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: rustup show
      - run: cargo clippy --workspace --all-targets --locked -- -D warnings
      - run: cargo doc --no-deps --workspace --locked
        env:
          RUSTDOCFLAGS: -D warnings
      - run: cargo test --workspace --locked --verbose
      - run: cargo build --workspace --locked
      - run: python3 scripts/smoke-messages.py
